name: build & deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm build
        cd docs/.vuepress/dist
        
    - name: Deploy Build Files
      env:
        # You should enroll ACEESS_TOKEN to repository's secret
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        git config --global user.email "wkhham@naver.com"
        git config --global user.name "goorm94"
        git init
        git add -A
        git commit -m 'deploy with vuepress'
        git push -f https://${ACCESS_TOKEN}@github.com:goorm94/blog.git master:gh-pages

        cd -
